# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d10291663d1de35f53458b13004c2e1f308dc49fd299cb1dbd15919410ed919c6b397e211ae0c961b296058df20ecb08f1130d4e094eeafc17deff40764d638

test:
  secret_key_base: c726518768f1a8529e83334225d1d8016a6d33bffac5e1d577f230ef1cf238d03de695e7555f91b28a5dc4c0163758c5fe2f0053ebf0a39b81700bd34144f318

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
